### ISSUE TITLE
Ubuntu: no execute rights for ImageJ after installation

### ISSUE THREAD

**Issue by DavidMoersdorf** [alexblaessle/PyFRAP#10]
after installation Embryo creation failed with the error message:

sh: 1: /home/lin2-local/Software/PyFRAP/pyfrp/executables/Fiji.app/ImageJ-linux64: Permission denied

-> no execute rights for ImageJ-linux64

**Comment by alexblaessle** [comment]
Should be fixed in commit https://github.com/alexblaessle/PyFRAP/commit/7792eccfb56bfe7b6fdb270ea1f8b262dd65f996. @DavidMoersdorf , can you confirm?

**Comment by DavidMoersdorf** [comment]
yep, fixed!
