### ISSUE TITLE
program doesn't start due to synthax error after last update on windows

### ISSUE THREAD

**Issue by hpreiss** [alexblaessle/PyFRAP#12]
![20161121_synthax error](https://cloud.githubusercontent.com/assets/23168388/20476212/19c5f842-afd0-11e6-984e-0cb178e7553b.png)

**Comment by alexblaessle** [comment]
The syntax error is witihin a python module of Fiji, but should not affect PyFRAP. The problem is that PyFRAP requires solid python since commit https://github.com/alexblaessle/PyFRAP/commit/0c8f19426c3a9f24c502126cad620558d46dc392 . You call install it via

```bash
pip install solidpython
```
