### ISSUE TITLE
Cannot find path under Windows

### ISSUE THREAD

**Issue by DavidMoersdorf** [alexblaessle/PyFRAP#6]
When trying to prepare .czi files to create an embryo file:
"The system cannot find the path specified.
mv: cannot stat '\\f......': No such file or directory"

**Comment by alexblaessle** [comment]
This was probably due to bad paths in Windows. 

Should be fixed in commit https://github.com/alexblaessle/PyFRAP/commit/c8cef017b19fd6f1d72bd84d60b39a68cdd485ef . @DavidMoersdorf , can you please pull the newest version and confirm?

**Comment by DavidMoersdorf** [comment]
Worked in previous version!

**Comment by alexblaessle** [comment]
Tested and works. Closed.
